### ISSUE TITLE
Migrate hackclub/slackin features to unified codebase

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/slackin#4]
From https://www.notion.so/2017-06-20-Classifying-Hack-Club-s-Repos-080c12f5662445cbad742b1dbb6986c1

- Greeter page needs to go in `frontend` 
-  `api` Endpoint for requesting Slack activity badges
- Slack invitation logic needs to go in `api` 
	- Example API request:

			 curl -X POST 'https://YOUR-SLACK-TEAM.slack.com/api/users.admin.invite' \
			 --data 'email=EMAIL&token=TOKEN&set_active=true' \
			 --compressed

**Comment by paked** [comment]
Closed in [hackclub/monoltih#16](hackclub/monolith/pull/16)
